M48
; DRILL file {KiCad 8.0.1} date 2024-04-22T16:58:15+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-22T16:58:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X99.76Y-57.1
X99.76Y-64.3
T2
X87.642Y-79.045
X99.072Y-79.045
M30
